INFO - 2021-08-31 10:56:49,080 - new_apply_order.py[line:450]: 开始第 borrowme【1】次进件……
INFO - 2021-08-31 10:56:49,081 - new_apply_order.py[line:79]: ======【nga测试环境】生成手机号：01630378609 ======
INFO - 2021-08-31 10:56:49,462 - new_apply_order.py[line:86]: 01630378609 检测用户存在成功！
INFO - 2021-08-31 10:56:49,512 - new_apply_order.py[line:93]: 01630378609 短信发送成功！
INFO - 2021-08-31 10:56:49,553 - new_apply_order.py[line:103]: 01630378609 注册成功！
ERROR - 2021-08-31 10:56:49,587 - new_apply_order.py[line:122]: 登录失败!
INFO - 2021-08-31 10:56:49,658 - new_apply_order.py[line:166]: 个人信息提交成功！
INFO - 2021-08-31 10:56:49,713 - new_apply_order.py[line:175]: 联系人信息提交成功！
ERROR - 2021-08-31 10:56:49,853 - new_apply_order.py[line:194]: 创建预审失败{"code":"9999","msg":"The Server is busy, Please try again later","data":null}
INFO - 2021-08-31 10:56:49,865 - new_apply_order.py[line:200]: 预审状态修改为通过,更新条数 0
INFO - 2021-08-31 10:56:49,873 - new_apply_order.py[line:203]: 更新初始额度！更新条数 0
INFO - 2021-08-31 10:56:50,186 - new_apply_order.py[line:215]: 活体图片上传成功！回写配置文件global_param.mp4_url
INFO - 2021-08-31 10:56:50,232 - new_apply_order.py[line:224]: 视频认证通过！
INFO - 2021-08-31 10:56:51,279 - new_apply_order.py[line:270]: bvn和银行卡绑卡认证通过！
INFO - 2021-08-31 10:56:51,577 - new_apply_order.py[line:291]: user更新1条
ERROR - 2021-08-31 10:56:51,819 - new_apply_order.py[line:319]: {"code":"50001004","msg":"Not eligible for borrowing","data":null}
INFO - 2021-08-31 10:56:52,290 - new_apply_order.py[line:326]: 查询loan_order_id成功！
INFO - 2021-08-31 10:56:52,320 - new_apply_order.py[line:336]: 订单回调复审通过成功！
INFO - 2021-08-31 10:56:53,061 - new_apply_order.py[line:353]: 获取token成功！token=bearer bf51653c-283e-47c5-b902-66a96a35688d！
INFO - 2021-08-31 10:56:53,508 - new_apply_order.py[line:326]: 查询loan_order_id成功！
INFO - 2021-08-31 10:56:54,050 - new_apply_order.py[line:365]: 后台已触发放款成功！
INFO - 2021-08-31 10:56:54,059 - new_apply_order.py[line:373]: xxl_job web 登录成功！
INFO - 2021-08-31 10:56:54,067 - new_apply_order.py[line:380]: xxl_job 放款准备作业执行成功！
INFO - 2021-08-31 10:56:55,486 - new_apply_order.py[line:326]: 查询loan_order_id成功！
INFO - 2021-08-31 10:56:55,503 - new_apply_order.py[line:385]: 修改放款准备完成时间成功！
INFO - 2021-08-31 10:56:55,511 - new_apply_order.py[line:388]: xxl_job 放款完成作业执行成功！
INFO - 2021-08-31 10:56:55,815 - new_apply_order.py[line:473]: 校验重试查询第1次
ERROR - 2021-08-31 10:56:56,832 - new_apply_order.py[line:431]: 放款完成或准备失败,目前的订单状态是32
INFO - 2021-08-31 10:56:56,832 - new_apply_order.py[line:432]: {'app': 'borrowme', 'loan_order_id': '1432507683397570560', 'mobile': '01630371420', 'order_status': 32}
INFO - 2021-08-31 10:56:56,841 - new_apply_order.py[line:373]: xxl_job web 登录成功！
INFO - 2021-08-31 10:56:56,850 - new_apply_order.py[line:380]: xxl_job 放款准备作业执行成功！
INFO - 2021-08-31 10:56:58,277 - new_apply_order.py[line:326]: 查询loan_order_id成功！
INFO - 2021-08-31 10:56:58,294 - new_apply_order.py[line:385]: 修改放款准备完成时间成功！
INFO - 2021-08-31 10:56:58,300 - new_apply_order.py[line:388]: xxl_job 放款完成作业执行成功！
INFO - 2021-08-31 10:56:58,805 - new_apply_order.py[line:473]: 校验重试查询第2次
ERROR - 2021-08-31 10:56:59,821 - new_apply_order.py[line:431]: 放款完成或准备失败,目前的订单状态是32
INFO - 2021-08-31 10:56:59,821 - new_apply_order.py[line:432]: {'app': 'borrowme', 'loan_order_id': '1432507683397570560', 'mobile': '01630371420', 'order_status': 32}
INFO - 2021-08-31 10:56:59,830 - new_apply_order.py[line:373]: xxl_job web 登录成功！
INFO - 2021-08-31 10:56:59,837 - new_apply_order.py[line:380]: xxl_job 放款准备作业执行成功！
INFO - 2021-08-31 10:57:01,259 - new_apply_order.py[line:326]: 查询loan_order_id成功！
INFO - 2021-08-31 10:57:01,271 - new_apply_order.py[line:385]: 修改放款准备完成时间成功！
INFO - 2021-08-31 10:57:01,276 - new_apply_order.py[line:388]: xxl_job 放款完成作业执行成功！
INFO - 2021-08-31 10:57:01,777 - new_apply_order.py[line:473]: 校验重试查询第3次
ERROR - 2021-08-31 10:57:02,789 - new_apply_order.py[line:431]: 放款完成或准备失败,目前的订单状态是32
INFO - 2021-08-31 10:57:02,790 - new_apply_order.py[line:432]: {'app': 'borrowme', 'loan_order_id': '1432507683397570560', 'mobile': '01630371420', 'order_status': 32}
INFO - 2021-08-31 10:57:02,799 - new_apply_order.py[line:373]: xxl_job web 登录成功！
INFO - 2021-08-31 10:57:02,807 - new_apply_order.py[line:380]: xxl_job 放款准备作业执行成功！
INFO - 2021-08-31 10:57:04,237 - new_apply_order.py[line:326]: 查询loan_order_id成功！
INFO - 2021-08-31 10:57:04,253 - new_apply_order.py[line:385]: 修改放款准备完成时间成功！
INFO - 2021-08-31 10:57:04,260 - new_apply_order.py[line:388]: xxl_job 放款完成作业执行成功！
INFO - 2021-08-31 10:57:04,765 - new_apply_order.py[line:473]: 校验重试查询第4次
ERROR - 2021-08-31 10:57:05,781 - new_apply_order.py[line:431]: 放款完成或准备失败,目前的订单状态是32
INFO - 2021-08-31 10:57:05,782 - new_apply_order.py[line:432]: {'app': 'borrowme', 'loan_order_id': '1432507683397570560', 'mobile': '01630371420', 'order_status': 32}
INFO - 2021-08-31 10:57:05,790 - new_apply_order.py[line:373]: xxl_job web 登录成功！
INFO - 2021-08-31 10:57:05,798 - new_apply_order.py[line:380]: xxl_job 放款准备作业执行成功！
INFO - 2021-08-31 10:57:07,218 - new_apply_order.py[line:326]: 查询loan_order_id成功！
INFO - 2021-08-31 10:57:07,234 - new_apply_order.py[line:385]: 修改放款准备完成时间成功！
INFO - 2021-08-31 10:57:07,241 - new_apply_order.py[line:388]: xxl_job 放款完成作业执行成功！
INFO - 2021-08-31 10:57:07,742 - new_apply_order.py[line:473]: 校验重试查询第5次
ERROR - 2021-08-31 10:57:08,756 - new_apply_order.py[line:431]: 放款完成或准备失败,目前的订单状态是32
INFO - 2021-08-31 10:57:08,756 - new_apply_order.py[line:432]: {'app': 'borrowme', 'loan_order_id': '1432507683397570560', 'mobile': '01630371420', 'order_status': 32}
INFO - 2021-08-31 10:57:08,762 - new_apply_order.py[line:373]: xxl_job web 登录成功！
INFO - 2021-08-31 10:57:08,769 - new_apply_order.py[line:380]: xxl_job 放款准备作业执行成功！
INFO - 2021-08-31 10:57:10,222 - new_apply_order.py[line:326]: 查询loan_order_id成功！
INFO - 2021-08-31 10:57:10,237 - new_apply_order.py[line:385]: 修改放款准备完成时间成功！
INFO - 2021-08-31 10:57:10,245 - new_apply_order.py[line:388]: xxl_job 放款完成作业执行成功！
INFO - 2021-08-31 10:57:10,748 - new_apply_order.py[line:473]: 校验重试查询第6次
ERROR - 2021-08-31 10:57:11,761 - new_apply_order.py[line:431]: 放款完成或准备失败,目前的订单状态是32
INFO - 2021-08-31 10:57:11,762 - new_apply_order.py[line:432]: {'app': 'borrowme', 'loan_order_id': '1432507683397570560', 'mobile': '01630371420', 'order_status': 32}
INFO - 2021-08-31 10:57:11,767 - new_apply_order.py[line:373]: xxl_job web 登录成功！
INFO - 2021-08-31 10:57:11,773 - new_apply_order.py[line:380]: xxl_job 放款准备作业执行成功！
INFO - 2021-08-31 10:57:13,197 - new_apply_order.py[line:326]: 查询loan_order_id成功！
INFO - 2021-08-31 10:57:13,217 - new_apply_order.py[line:385]: 修改放款准备完成时间成功！
INFO - 2021-08-31 10:57:13,223 - new_apply_order.py[line:388]: xxl_job 放款完成作业执行成功！
INFO - 2021-08-31 10:57:13,727 - new_apply_order.py[line:473]: 校验重试查询第7次
ERROR - 2021-08-31 10:57:14,745 - new_apply_order.py[line:431]: 放款完成或准备失败,目前的订单状态是32
INFO - 2021-08-31 10:57:14,745 - new_apply_order.py[line:432]: {'app': 'borrowme', 'loan_order_id': '1432507683397570560', 'mobile': '01630371420', 'order_status': 32}
INFO - 2021-08-31 10:57:14,754 - new_apply_order.py[line:373]: xxl_job web 登录成功！
INFO - 2021-08-31 10:57:14,761 - new_apply_order.py[line:380]: xxl_job 放款准备作业执行成功！
INFO - 2021-08-31 10:57:16,232 - new_apply_order.py[line:326]: 查询loan_order_id成功！
INFO - 2021-08-31 10:57:16,245 - new_apply_order.py[line:385]: 修改放款准备完成时间成功！
INFO - 2021-08-31 10:57:16,254 - new_apply_order.py[line:388]: xxl_job 放款完成作业执行成功！
INFO - 2021-08-31 10:57:16,756 - new_apply_order.py[line:473]: 校验重试查询第8次
ERROR - 2021-08-31 10:57:17,764 - new_apply_order.py[line:431]: 放款完成或准备失败,目前的订单状态是32
INFO - 2021-08-31 10:57:17,764 - new_apply_order.py[line:432]: {'app': 'borrowme', 'loan_order_id': '1432507683397570560', 'mobile': '01630371420', 'order_status': 32}
INFO - 2021-08-31 10:57:17,771 - new_apply_order.py[line:373]: xxl_job web 登录成功！
INFO - 2021-08-31 10:57:17,777 - new_apply_order.py[line:380]: xxl_job 放款准备作业执行成功！
INFO - 2021-08-31 10:57:19,195 - new_apply_order.py[line:326]: 查询loan_order_id成功！
INFO - 2021-08-31 10:57:19,212 - new_apply_order.py[line:385]: 修改放款准备完成时间成功！
INFO - 2021-08-31 10:57:19,220 - new_apply_order.py[line:388]: xxl_job 放款完成作业执行成功！
INFO - 2021-08-31 10:57:19,721 - new_apply_order.py[line:473]: 校验重试查询第9次
ERROR - 2021-08-31 10:57:20,737 - new_apply_order.py[line:431]: 放款完成或准备失败,目前的订单状态是32
INFO - 2021-08-31 10:57:20,738 - new_apply_order.py[line:432]: {'app': 'borrowme', 'loan_order_id': '1432507683397570560', 'mobile': '01630371420', 'order_status': 32}
INFO - 2021-08-31 10:57:20,746 - new_apply_order.py[line:373]: xxl_job web 登录成功！
INFO - 2021-08-31 10:57:20,753 - new_apply_order.py[line:380]: xxl_job 放款准备作业执行成功！
INFO - 2021-08-31 10:57:22,181 - new_apply_order.py[line:326]: 查询loan_order_id成功！
INFO - 2021-08-31 10:57:22,200 - new_apply_order.py[line:385]: 修改放款准备完成时间成功！
INFO - 2021-08-31 10:57:22,206 - new_apply_order.py[line:388]: xxl_job 放款完成作业执行成功！
INFO - 2021-08-31 10:57:22,709 - new_apply_order.py[line:473]: 校验重试查询第10次
ERROR - 2021-08-31 10:57:23,720 - new_apply_order.py[line:431]: 放款完成或准备失败,目前的订单状态是32
INFO - 2021-08-31 10:57:23,721 - new_apply_order.py[line:432]: {'app': 'borrowme', 'loan_order_id': '1432507683397570560', 'mobile': '01630371420', 'order_status': 32}
INFO - 2021-08-31 10:57:23,728 - new_apply_order.py[line:373]: xxl_job web 登录成功！
INFO - 2021-08-31 10:57:23,735 - new_apply_order.py[line:380]: xxl_job 放款准备作业执行成功！
INFO - 2021-08-31 10:57:25,165 - new_apply_order.py[line:326]: 查询loan_order_id成功！
INFO - 2021-08-31 10:57:25,180 - new_apply_order.py[line:385]: 修改放款准备完成时间成功！
INFO - 2021-08-31 10:57:25,186 - new_apply_order.py[line:388]: xxl_job 放款完成作业执行成功！
INFO - 2021-08-31 10:57:25,688 - new_apply_order.py[line:490]: ===========完成第【1】次进件===========
INFO - 2021-08-31 10:57:25,688 - new_apply_order.py[line:493]: ======完成第【1】次进件,耗时36.61s=====
