INFO - 2021-11-27 11:04:54,742 - new_apply_order.py[line:882]: 开始第 kencash【1】次进件……
INFO - 2021-11-27 11:04:54,742 - new_apply_order.py[line:84]: ======【ke测试环境】生成手机号：737982294 ======
INFO - 2021-11-27 11:04:55,131 - new_apply_order.py[line:97]: 737982294 检测用户存在成功！
INFO - 2021-11-27 11:04:55,195 - new_apply_order.py[line:106]: 737982294 短信发送成功！
INFO - 2021-11-27 11:04:55,261 - new_apply_order.py[line:119]: 737982294 注册成功！
INFO - 2021-11-27 11:04:55,326 - new_apply_order.py[line:135]: 737982294 登录短信发送成功！
INFO - 2021-11-27 11:04:55,417 - new_apply_order.py[line:145]: userId=6235819447069712384,mobile=737982294,token=35af4b2fe00b114ed165743a488122ae 登录成功
INFO - 2021-11-27 11:04:55,563 - new_apply_order.py[line:212]: 个人信息提交成功！
INFO - 2021-11-27 11:04:55,632 - new_apply_order.py[line:232]: 联系人信息提交成功！
INFO - 2021-11-27 11:04:56,082 - new_apply_order.py[line:255]: 创建预审订单成功！
INFO - 2021-11-27 11:04:56,104 - new_apply_order.py[line:263]: 预审状态修改为通过,更新条数 1
INFO - 2021-11-27 11:04:56,120 - new_apply_order.py[line:266]: 更新初始额度！更新条数 1
INFO - 2021-11-27 11:04:56,397 - new_apply_order.py[line:342]: 活体图片上传成功！回写配置文件global_param.mp4_url
INFO - 2021-11-27 11:04:56,440 - new_apply_order.py[line:352]: 视频认证通过！
ERROR - 2021-11-27 11:04:56,670 - new_apply_order.py[line:579]: 绑卡失败！{"code":"60001004","msg":"The OTP has expired.please regenerate OTP to try again","data":null}
INFO - 2021-11-27 11:04:56,908 - new_apply_order.py[line:612]: 进件成功！执行sql将订单改为风控中……
INFO - 2021-11-27 11:04:57,950 - new_apply_order.py[line:618]: 订单表更新1条，信审更新1条
INFO - 2021-11-27 11:04:58,348 - new_apply_order.py[line:632]: 查询loan_order_id成功！
INFO - 2021-11-27 11:04:58,406 - new_apply_order.py[line:647]: 订单回调复审通过成功！
INFO - 2021-11-27 11:04:59,364 - new_apply_order.py[line:669]: 获取token成功！token=bearer 5030f87c-443a-4424-87a0-97baa535a867！
INFO - 2021-11-27 11:04:59,760 - new_apply_order.py[line:632]: 查询loan_order_id成功！
INFO - 2021-11-27 11:05:00,465 - new_apply_order.py[line:687]: 后台已触发放款成功！
INFO - 2021-11-27 11:05:00,489 - new_apply_order.py[line:701]: xxl_job web 登录成功！
INFO - 2021-11-27 11:05:00,504 - new_apply_order.py[line:717]: xxl_job 放款准备作业执行成功！
INFO - 2021-11-27 11:05:01,867 - new_apply_order.py[line:632]: 查询loan_order_id成功！
INFO - 2021-11-27 11:05:01,876 - new_apply_order.py[line:725]: 修改放款准备完成时间成功！
INFO - 2021-11-27 11:05:01,884 - new_apply_order.py[line:733]: xxl_job 放款完成作业执行成功！
INFO - 2021-11-27 11:05:02,258 - new_apply_order.py[line:632]: 查询loan_order_id成功！
INFO - 2021-11-27 11:05:02,572 - new_apply_order.py[line:905]: 校验重试查询第1次
ERROR - 2021-11-27 11:05:03,587 - new_apply_order.py[line:801]: 放款完成或准备失败,目前的订单状态是30
INFO - 2021-11-27 11:05:03,588 - new_apply_order.py[line:802]: {'app': 'kencash', 'loan_order_id': '1464430005508902912', 'mobile': '737982294', 'order_status': 30}
INFO - 2021-11-27 11:05:03,588 - new_apply_order.py[line:905]: 校验重试查询第2次
ERROR - 2021-11-27 11:05:04,601 - new_apply_order.py[line:801]: 放款完成或准备失败,目前的订单状态是30
INFO - 2021-11-27 11:05:04,601 - new_apply_order.py[line:802]: {'app': 'kencash', 'loan_order_id': '1464430005508902912', 'mobile': '737982294', 'order_status': 30}
INFO - 2021-11-27 11:05:04,602 - new_apply_order.py[line:905]: 校验重试查询第3次
ERROR - 2021-11-27 11:05:05,620 - new_apply_order.py[line:801]: 放款完成或准备失败,目前的订单状态是30
INFO - 2021-11-27 11:05:05,620 - new_apply_order.py[line:802]: {'app': 'kencash', 'loan_order_id': '1464430005508902912', 'mobile': '737982294', 'order_status': 30}
INFO - 2021-11-27 11:05:05,620 - new_apply_order.py[line:905]: 校验重试查询第4次
ERROR - 2021-11-27 11:05:06,634 - new_apply_order.py[line:801]: 放款完成或准备失败,目前的订单状态是30
INFO - 2021-11-27 11:05:06,634 - new_apply_order.py[line:802]: {'app': 'kencash', 'loan_order_id': '1464430005508902912', 'mobile': '737982294', 'order_status': 30}
INFO - 2021-11-27 11:05:06,635 - new_apply_order.py[line:905]: 校验重试查询第5次
ERROR - 2021-11-27 11:05:07,651 - new_apply_order.py[line:801]: 放款完成或准备失败,目前的订单状态是30
INFO - 2021-11-27 11:05:07,651 - new_apply_order.py[line:802]: {'app': 'kencash', 'loan_order_id': '1464430005508902912', 'mobile': '737982294', 'order_status': 30}
INFO - 2021-11-27 11:05:07,652 - new_apply_order.py[line:905]: 校验重试查询第6次
ERROR - 2021-11-27 11:05:08,669 - new_apply_order.py[line:801]: 放款完成或准备失败,目前的订单状态是30
INFO - 2021-11-27 11:05:08,670 - new_apply_order.py[line:802]: {'app': 'kencash', 'loan_order_id': '1464430005508902912', 'mobile': '737982294', 'order_status': 30}
INFO - 2021-11-27 11:05:08,670 - new_apply_order.py[line:905]: 校验重试查询第7次
ERROR - 2021-11-27 11:05:09,686 - new_apply_order.py[line:801]: 放款完成或准备失败,目前的订单状态是30
INFO - 2021-11-27 11:05:09,687 - new_apply_order.py[line:802]: {'app': 'kencash', 'loan_order_id': '1464430005508902912', 'mobile': '737982294', 'order_status': 30}
INFO - 2021-11-27 11:05:09,687 - new_apply_order.py[line:905]: 校验重试查询第8次
ERROR - 2021-11-27 11:05:10,699 - new_apply_order.py[line:801]: 放款完成或准备失败,目前的订单状态是30
INFO - 2021-11-27 11:05:10,699 - new_apply_order.py[line:802]: {'app': 'kencash', 'loan_order_id': '1464430005508902912', 'mobile': '737982294', 'order_status': 30}
INFO - 2021-11-27 11:05:10,699 - new_apply_order.py[line:905]: 校验重试查询第9次
ERROR - 2021-11-27 11:05:11,714 - new_apply_order.py[line:801]: 放款完成或准备失败,目前的订单状态是30
INFO - 2021-11-27 11:05:11,714 - new_apply_order.py[line:802]: {'app': 'kencash', 'loan_order_id': '1464430005508902912', 'mobile': '737982294', 'order_status': 30}
INFO - 2021-11-27 11:05:11,715 - new_apply_order.py[line:905]: 校验重试查询第10次
ERROR - 2021-11-27 11:05:12,732 - new_apply_order.py[line:801]: 放款完成或准备失败,目前的订单状态是30
INFO - 2021-11-27 11:05:12,732 - new_apply_order.py[line:802]: {'app': 'kencash', 'loan_order_id': '1464430005508902912', 'mobile': '737982294', 'order_status': 30}
INFO - 2021-11-27 11:05:12,732 - new_apply_order.py[line:922]: ===========完成第【1】次进件===========
INFO - 2021-11-27 11:05:12,732 - new_apply_order.py[line:925]: ======完成第【1】次进件,耗时17.99s=====
