INFO - 2021-12-02 14:22:55,967 - new_apply_order.py[line:882]: 开始第 G_Prestamo【1】次进件……
INFO - 2021-12-02 14:22:56,149 - new_apply_order.py[line:75]: 更新脏数据0条
INFO - 2021-12-02 14:22:56,149 - new_apply_order.py[line:84]: ======【mx测试环境】生成手机号：1638426175 ======
INFO - 2021-12-02 14:22:56,545 - new_apply_order.py[line:97]: 1638426175 检测用户存在成功！
INFO - 2021-12-02 14:22:56,644 - new_apply_order.py[line:106]: 1638426175 短信发送成功！
INFO - 2021-12-02 14:22:56,707 - new_apply_order.py[line:119]: 1638426175 注册成功！
INFO - 2021-12-02 14:22:56,782 - new_apply_order.py[line:135]: 1638426175 登录短信发送成功！
INFO - 2021-12-02 14:22:56,841 - new_apply_order.py[line:145]: userId=4979390020846886912,mobile=1638426175,token=c3c6ab22cc6faac6e45ce7bbd8dbf8a9 登录成功
INFO - 2021-12-02 14:22:56,990 - new_apply_order.py[line:212]: 个人信息提交成功！
INFO - 2021-12-02 14:22:57,687 - new_apply_order.py[line:255]: 创建预审订单成功！
INFO - 2021-12-02 14:22:57,702 - new_apply_order.py[line:263]: 预审状态修改为通过,更新条数 1
INFO - 2021-12-02 14:22:57,717 - new_apply_order.py[line:266]: 更新初始额度！更新条数 1
INFO - 2021-12-02 14:23:00,463 - new_apply_order.py[line:361]: curp上传成功!
INFO - 2021-12-02 14:23:00,660 - new_apply_order.py[line:370]: curp_rfc校验通过！
INFO - 2021-12-02 14:23:01,528 - new_apply_order.py[line:381]: 人脸识别成功!
INFO - 2021-12-02 14:23:02,219 - new_apply_order.py[line:568]: 绑卡成功！
INFO - 2021-12-02 14:23:02,508 - new_apply_order.py[line:612]: 进件成功！执行sql将订单改为风控中……
INFO - 2021-12-02 14:23:03,546 - new_apply_order.py[line:618]: 订单表更新1条，信审更新1条
INFO - 2021-12-02 14:23:03,909 - new_apply_order.py[line:632]: 查询loan_order_id成功！
INFO - 2021-12-02 14:23:03,981 - new_apply_order.py[line:647]: 订单回调复审通过成功！
INFO - 2021-12-02 14:23:04,782 - new_apply_order.py[line:669]: 获取token成功！token=bearer 6b19e5b1-df3c-4a4c-9658-b6bb8858121b！
INFO - 2021-12-02 14:23:05,138 - new_apply_order.py[line:632]: 查询loan_order_id成功！
INFO - 2021-12-02 14:23:05,692 - new_apply_order.py[line:687]: 后台已触发放款成功！
INFO - 2021-12-02 14:23:05,710 - new_apply_order.py[line:701]: xxl_job web 登录成功！
INFO - 2021-12-02 14:23:05,725 - new_apply_order.py[line:717]: xxl_job 放款准备作业执行成功！
INFO - 2021-12-02 14:23:07,085 - new_apply_order.py[line:632]: 查询loan_order_id成功！
INFO - 2021-12-02 14:23:07,101 - new_apply_order.py[line:725]: 修改放款准备完成时间成功！
INFO - 2021-12-02 14:23:07,109 - new_apply_order.py[line:733]: xxl_job 放款完成作业执行成功！
INFO - 2021-12-02 14:23:07,467 - new_apply_order.py[line:632]: 查询loan_order_id成功！
INFO - 2021-12-02 14:23:07,783 - new_apply_order.py[line:905]: 校验重试查询第1次
ERROR - 2021-12-02 14:23:08,801 - new_apply_order.py[line:801]: 放款完成或准备失败,目前的订单状态是35
INFO - 2021-12-02 14:23:08,801 - new_apply_order.py[line:802]: {'app': 'G_Prestamo', 'loan_order_id': '1466291778931134464', 'mobile': '1638426175', 'order_status': 35}
INFO - 2021-12-02 14:23:09,659 - new_apply_order.py[line:632]: 查询loan_order_id成功！
INFO - 2021-12-02 14:23:09,808 - new_apply_order.py[line:754]: 放款回调成功！
INFO - 2021-12-02 14:23:09,809 - new_apply_order.py[line:905]: 校验重试查询第2次
INFO - 2021-12-02 14:23:10,819 - new_apply_order.py[line:799]: 放款完成或准备成功,目前的订单状态是40
INFO - 2021-12-02 14:23:10,819 - new_apply_order.py[line:802]: {'app': 'G_Prestamo', 'loan_order_id': '1466291778931134464', 'mobile': '1638426175', 'order_status': 40}
INFO - 2021-12-02 14:23:10,821 - new_apply_order.py[line:922]: ===========完成第【1】次进件===========
INFO - 2021-12-02 14:23:10,821 - new_apply_order.py[line:925]: ======完成第【1】次进件,耗时14.85s=====
