INFO - 2021-08-31 13:48:15,988 - new_apply_order.py[line:517]: 开始第 borrowme【1】次进件……
INFO - 2021-08-31 13:48:15,988 - new_apply_order.py[line:79]: ======【nga测试环境】生成手机号：01630388895 ======
INFO - 2021-08-31 13:48:16,366 - new_apply_order.py[line:86]: 01630388895 检测用户存在成功！
INFO - 2021-08-31 13:48:16,416 - new_apply_order.py[line:93]: 01630388895 短信发送成功！
INFO - 2021-08-31 13:48:16,456 - new_apply_order.py[line:103]: 01630388895 注册成功！
INFO - 2021-08-31 13:48:16,507 - new_apply_order.py[line:113]: 01630388895 登录短信发送成功！
ERROR - 2021-08-31 13:48:16,531 - new_apply_order.py[line:128]: 登录失败!
INFO - 2021-08-31 13:48:16,587 - new_apply_order.py[line:172]: 个人信息提交成功！
INFO - 2021-08-31 13:48:16,634 - new_apply_order.py[line:181]: 联系人信息提交成功！
ERROR - 2021-08-31 13:48:16,779 - new_apply_order.py[line:200]: 创建预审失败{"code":"9999","msg":"The Server is busy, Please try again later","data":null}
INFO - 2021-08-31 13:48:16,792 - new_apply_order.py[line:206]: 预审状态修改为通过,更新条数 0
INFO - 2021-08-31 13:48:16,801 - new_apply_order.py[line:209]: 更新初始额度！更新条数 0
INFO - 2021-08-31 13:48:17,050 - new_apply_order.py[line:221]: 活体图片上传成功！回写配置文件global_param.mp4_url
INFO - 2021-08-31 13:48:17,081 - new_apply_order.py[line:230]: 视频认证通过！
INFO - 2021-08-31 13:48:18,069 - new_apply_order.py[line:276]: bvn和银行卡绑卡认证通过！
INFO - 2021-08-31 13:48:18,356 - new_apply_order.py[line:297]: user更新1条
ERROR - 2021-08-31 13:48:18,516 - new_apply_order.py[line:325]: {"code":"50001004","msg":"Not eligible for borrowing","data":null}
INFO - 2021-08-31 13:48:18,970 - new_apply_order.py[line:332]: 查询loan_order_id成功！
INFO - 2021-08-31 13:48:19,003 - new_apply_order.py[line:342]: 订单回调复审通过成功！
INFO - 2021-08-31 13:48:19,792 - new_apply_order.py[line:358]: 获取token成功！token=bearer bf51653c-283e-47c5-b902-66a96a35688d！
INFO - 2021-08-31 13:48:20,223 - new_apply_order.py[line:332]: 查询loan_order_id成功！
INFO - 2021-08-31 13:48:20,584 - new_apply_order.py[line:370]: 后台已触发放款成功！
INFO - 2021-08-31 13:48:40,248 - new_apply_order.py[line:378]: xxl_job web 登录成功！
INFO - 2021-08-31 13:48:40,256 - new_apply_order.py[line:385]: xxl_job 放款准备作业执行成功！
INFO - 2021-08-31 13:48:41,702 - new_apply_order.py[line:332]: 查询loan_order_id成功！
INFO - 2021-08-31 13:48:41,720 - new_apply_order.py[line:390]: 修改放款准备完成时间成功！
INFO - 2021-08-31 13:48:41,729 - new_apply_order.py[line:393]: xxl_job 放款完成作业执行成功！
INFO - 2021-08-31 13:48:42,033 - new_apply_order.py[line:540]: 校验重试查询第1次
ERROR - 2021-08-31 13:48:43,042 - new_apply_order.py[line:436]: 放款完成或准备失败,目前的订单状态是32
INFO - 2021-08-31 13:48:43,042 - new_apply_order.py[line:437]: {'app': 'borrowme', 'loan_order_id': '1432507683397570560', 'mobile': '01630371420', 'order_status': 32}
INFO - 2021-08-31 13:48:43,048 - new_apply_order.py[line:378]: xxl_job web 登录成功！
INFO - 2021-08-31 13:48:43,054 - new_apply_order.py[line:385]: xxl_job 放款准备作业执行成功！
INFO - 2021-08-31 13:48:44,506 - new_apply_order.py[line:332]: 查询loan_order_id成功！
INFO - 2021-08-31 13:48:44,521 - new_apply_order.py[line:390]: 修改放款准备完成时间成功！
INFO - 2021-08-31 13:48:44,526 - new_apply_order.py[line:393]: xxl_job 放款完成作业执行成功！
INFO - 2021-08-31 13:48:45,031 - new_apply_order.py[line:540]: 校验重试查询第2次
ERROR - 2021-08-31 13:48:46,046 - new_apply_order.py[line:436]: 放款完成或准备失败,目前的订单状态是32
INFO - 2021-08-31 13:48:46,047 - new_apply_order.py[line:437]: {'app': 'borrowme', 'loan_order_id': '1432507683397570560', 'mobile': '01630371420', 'order_status': 32}
INFO - 2021-08-31 13:48:46,056 - new_apply_order.py[line:378]: xxl_job web 登录成功！
INFO - 2021-08-31 13:48:46,063 - new_apply_order.py[line:385]: xxl_job 放款准备作业执行成功！
INFO - 2021-08-31 13:48:47,497 - new_apply_order.py[line:332]: 查询loan_order_id成功！
INFO - 2021-08-31 13:48:47,517 - new_apply_order.py[line:390]: 修改放款准备完成时间成功！
INFO - 2021-08-31 13:48:47,524 - new_apply_order.py[line:393]: xxl_job 放款完成作业执行成功！
INFO - 2021-08-31 13:48:48,029 - new_apply_order.py[line:540]: 校验重试查询第3次
ERROR - 2021-08-31 13:48:49,044 - new_apply_order.py[line:436]: 放款完成或准备失败,目前的订单状态是32
INFO - 2021-08-31 13:48:49,045 - new_apply_order.py[line:437]: {'app': 'borrowme', 'loan_order_id': '1432507683397570560', 'mobile': '01630371420', 'order_status': 32}
INFO - 2021-08-31 13:48:49,052 - new_apply_order.py[line:378]: xxl_job web 登录成功！
INFO - 2021-08-31 13:48:49,059 - new_apply_order.py[line:385]: xxl_job 放款准备作业执行成功！
INFO - 2021-08-31 13:48:50,498 - new_apply_order.py[line:332]: 查询loan_order_id成功！
INFO - 2021-08-31 13:48:50,510 - new_apply_order.py[line:390]: 修改放款准备完成时间成功！
INFO - 2021-08-31 13:48:50,514 - new_apply_order.py[line:393]: xxl_job 放款完成作业执行成功！
INFO - 2021-08-31 13:48:51,017 - new_apply_order.py[line:540]: 校验重试查询第4次
ERROR - 2021-08-31 13:48:52,026 - new_apply_order.py[line:436]: 放款完成或准备失败,目前的订单状态是32
INFO - 2021-08-31 13:48:52,026 - new_apply_order.py[line:437]: {'app': 'borrowme', 'loan_order_id': '1432507683397570560', 'mobile': '01630371420', 'order_status': 32}
INFO - 2021-08-31 13:48:52,031 - new_apply_order.py[line:378]: xxl_job web 登录成功！
INFO - 2021-08-31 13:48:52,035 - new_apply_order.py[line:385]: xxl_job 放款准备作业执行成功！
INFO - 2021-08-31 13:48:53,502 - new_apply_order.py[line:332]: 查询loan_order_id成功！
INFO - 2021-08-31 13:48:53,520 - new_apply_order.py[line:390]: 修改放款准备完成时间成功！
INFO - 2021-08-31 13:48:53,529 - new_apply_order.py[line:393]: xxl_job 放款完成作业执行成功！
INFO - 2021-08-31 13:48:54,032 - new_apply_order.py[line:540]: 校验重试查询第5次
ERROR - 2021-08-31 13:48:55,039 - new_apply_order.py[line:436]: 放款完成或准备失败,目前的订单状态是32
INFO - 2021-08-31 13:48:55,039 - new_apply_order.py[line:437]: {'app': 'borrowme', 'loan_order_id': '1432507683397570560', 'mobile': '01630371420', 'order_status': 32}
INFO - 2021-08-31 13:48:55,044 - new_apply_order.py[line:378]: xxl_job web 登录成功！
INFO - 2021-08-31 13:48:55,049 - new_apply_order.py[line:385]: xxl_job 放款准备作业执行成功！
INFO - 2021-08-31 13:48:56,470 - new_apply_order.py[line:332]: 查询loan_order_id成功！
INFO - 2021-08-31 13:48:56,482 - new_apply_order.py[line:390]: 修改放款准备完成时间成功！
INFO - 2021-08-31 13:48:56,488 - new_apply_order.py[line:393]: xxl_job 放款完成作业执行成功！
INFO - 2021-08-31 13:48:56,992 - new_apply_order.py[line:540]: 校验重试查询第6次
ERROR - 2021-08-31 13:48:58,002 - new_apply_order.py[line:436]: 放款完成或准备失败,目前的订单状态是32
INFO - 2021-08-31 13:48:58,003 - new_apply_order.py[line:437]: {'app': 'borrowme', 'loan_order_id': '1432507683397570560', 'mobile': '01630371420', 'order_status': 32}
INFO - 2021-08-31 13:48:58,008 - new_apply_order.py[line:378]: xxl_job web 登录成功！
INFO - 2021-08-31 13:48:58,014 - new_apply_order.py[line:385]: xxl_job 放款准备作业执行成功！
INFO - 2021-08-31 13:48:59,440 - new_apply_order.py[line:332]: 查询loan_order_id成功！
INFO - 2021-08-31 13:48:59,457 - new_apply_order.py[line:390]: 修改放款准备完成时间成功！
INFO - 2021-08-31 13:48:59,466 - new_apply_order.py[line:393]: xxl_job 放款完成作业执行成功！
INFO - 2021-08-31 13:48:59,967 - new_apply_order.py[line:540]: 校验重试查询第7次
