INFO - 2022-01-04 16:49:00,411 - new_apply_order.py[line:892]: 开始第 aceloan【1】次进件……
ERROR - 2022-01-04 16:49:00,717 - new_apply_order.py[line:938]: No option 'url' in section: 'global_param_aceloan'
ERROR - 2022-01-04 16:49:00,725 - new_apply_order.py[line:939]: None
