INFO - 2021-11-30 17:01:12,754 - new_apply_order.py[line:882]: 开始第 kencash【1】次进件……
INFO - 2021-11-30 17:01:12,755 - new_apply_order.py[line:84]: ======【ke测试环境】生成手机号：738262872 ======
INFO - 2021-11-30 17:01:14,889 - new_apply_order.py[line:97]: 738262872 检测用户存在成功！
INFO - 2021-11-30 17:01:15,220 - new_apply_order.py[line:106]: 738262872 短信发送成功！
INFO - 2021-11-30 17:01:16,108 - new_apply_order.py[line:119]: 738262872 注册成功！
INFO - 2021-11-30 17:01:16,218 - new_apply_order.py[line:135]: 738262872 登录短信发送成功！
INFO - 2021-11-30 17:01:17,491 - new_apply_order.py[line:145]: userId=6236996286786969600,mobile=738262872,token=420b9fba20345f5eed9a85ddacc984fd 登录成功
INFO - 2021-11-30 17:01:18,651 - new_apply_order.py[line:212]: 个人信息提交成功！
INFO - 2021-11-30 17:01:19,009 - new_apply_order.py[line:232]: 联系人信息提交成功！
INFO - 2021-11-30 17:01:19,825 - new_apply_order.py[line:255]: 创建预审订单成功！
INFO - 2021-11-30 17:01:19,849 - new_apply_order.py[line:263]: 预审状态修改为通过,更新条数 1
INFO - 2021-11-30 17:01:19,866 - new_apply_order.py[line:266]: 更新初始额度！更新条数 1
INFO - 2021-11-30 17:01:20,356 - new_apply_order.py[line:342]: 活体图片上传成功！回写配置文件global_param.mp4_url
INFO - 2021-11-30 17:01:20,513 - new_apply_order.py[line:352]: 视频认证通过！
ERROR - 2021-11-30 17:01:20,794 - new_apply_order.py[line:579]: 绑卡失败！{"code":"60001004","msg":"The OTP has expired.please regenerate OTP to try again","data":null}
INFO - 2021-11-30 17:01:21,368 - new_apply_order.py[line:612]: 进件成功！执行sql将订单改为风控中……
INFO - 2021-11-30 17:01:22,433 - new_apply_order.py[line:618]: 订单表更新1条，信审更新1条
INFO - 2021-11-30 17:01:23,002 - new_apply_order.py[line:632]: 查询loan_order_id成功！
INFO - 2021-11-30 17:01:23,086 - new_apply_order.py[line:647]: 订单回调复审通过成功！
INFO - 2021-11-30 17:01:23,920 - new_apply_order.py[line:669]: 获取token成功！token=bearer 6338ce83-f1f5-4732-ab15-b3b137c4810d！
INFO - 2021-11-30 17:01:24,310 - new_apply_order.py[line:632]: 查询loan_order_id成功！
INFO - 2021-11-30 17:01:24,701 - new_apply_order.py[line:687]: 后台已触发放款成功！
INFO - 2021-11-30 17:01:24,727 - new_apply_order.py[line:701]: xxl_job web 登录成功！
INFO - 2021-11-30 17:01:24,741 - new_apply_order.py[line:717]: xxl_job 放款准备作业执行成功！
INFO - 2021-11-30 17:01:26,149 - new_apply_order.py[line:632]: 查询loan_order_id成功！
INFO - 2021-11-30 17:01:26,162 - new_apply_order.py[line:725]: 修改放款准备完成时间成功！
INFO - 2021-11-30 17:01:26,168 - new_apply_order.py[line:733]: xxl_job 放款完成作业执行成功！
INFO - 2021-11-30 17:01:26,538 - new_apply_order.py[line:632]: 查询loan_order_id成功！
INFO - 2021-11-30 17:01:26,855 - new_apply_order.py[line:905]: 校验重试查询第1次
ERROR - 2021-11-30 17:01:27,871 - new_apply_order.py[line:801]: 放款完成或准备失败,目前的订单状态是30
INFO - 2021-11-30 17:01:27,872 - new_apply_order.py[line:802]: {'app': 'kencash', 'loan_order_id': '1465606858747940864', 'mobile': '738262872', 'order_status': 30}
INFO - 2021-11-30 17:01:27,872 - new_apply_order.py[line:905]: 校验重试查询第2次
ERROR - 2021-11-30 17:01:28,887 - new_apply_order.py[line:801]: 放款完成或准备失败,目前的订单状态是30
INFO - 2021-11-30 17:01:28,887 - new_apply_order.py[line:802]: {'app': 'kencash', 'loan_order_id': '1465606858747940864', 'mobile': '738262872', 'order_status': 30}
INFO - 2021-11-30 17:01:28,887 - new_apply_order.py[line:905]: 校验重试查询第3次
ERROR - 2021-11-30 17:01:29,902 - new_apply_order.py[line:801]: 放款完成或准备失败,目前的订单状态是30
INFO - 2021-11-30 17:01:29,903 - new_apply_order.py[line:802]: {'app': 'kencash', 'loan_order_id': '1465606858747940864', 'mobile': '738262872', 'order_status': 30}
INFO - 2021-11-30 17:01:29,903 - new_apply_order.py[line:905]: 校验重试查询第4次
ERROR - 2021-11-30 17:01:30,920 - new_apply_order.py[line:801]: 放款完成或准备失败,目前的订单状态是30
INFO - 2021-11-30 17:01:30,920 - new_apply_order.py[line:802]: {'app': 'kencash', 'loan_order_id': '1465606858747940864', 'mobile': '738262872', 'order_status': 30}
INFO - 2021-11-30 17:01:30,920 - new_apply_order.py[line:905]: 校验重试查询第5次
ERROR - 2021-11-30 17:01:31,935 - new_apply_order.py[line:801]: 放款完成或准备失败,目前的订单状态是30
INFO - 2021-11-30 17:01:31,935 - new_apply_order.py[line:802]: {'app': 'kencash', 'loan_order_id': '1465606858747940864', 'mobile': '738262872', 'order_status': 30}
INFO - 2021-11-30 17:01:31,935 - new_apply_order.py[line:905]: 校验重试查询第6次
ERROR - 2021-11-30 17:01:32,949 - new_apply_order.py[line:801]: 放款完成或准备失败,目前的订单状态是30
INFO - 2021-11-30 17:01:32,950 - new_apply_order.py[line:802]: {'app': 'kencash', 'loan_order_id': '1465606858747940864', 'mobile': '738262872', 'order_status': 30}
INFO - 2021-11-30 17:01:32,950 - new_apply_order.py[line:905]: 校验重试查询第7次
ERROR - 2021-11-30 17:01:33,965 - new_apply_order.py[line:801]: 放款完成或准备失败,目前的订单状态是30
INFO - 2021-11-30 17:01:33,965 - new_apply_order.py[line:802]: {'app': 'kencash', 'loan_order_id': '1465606858747940864', 'mobile': '738262872', 'order_status': 30}
INFO - 2021-11-30 17:01:33,966 - new_apply_order.py[line:905]: 校验重试查询第8次
ERROR - 2021-11-30 17:01:34,985 - new_apply_order.py[line:801]: 放款完成或准备失败,目前的订单状态是30
INFO - 2021-11-30 17:01:34,986 - new_apply_order.py[line:802]: {'app': 'kencash', 'loan_order_id': '1465606858747940864', 'mobile': '738262872', 'order_status': 30}
INFO - 2021-11-30 17:01:34,986 - new_apply_order.py[line:905]: 校验重试查询第9次
ERROR - 2021-11-30 17:01:36,002 - new_apply_order.py[line:801]: 放款完成或准备失败,目前的订单状态是30
INFO - 2021-11-30 17:01:36,002 - new_apply_order.py[line:802]: {'app': 'kencash', 'loan_order_id': '1465606858747940864', 'mobile': '738262872', 'order_status': 30}
INFO - 2021-11-30 17:01:36,002 - new_apply_order.py[line:905]: 校验重试查询第10次
ERROR - 2021-11-30 17:01:37,014 - new_apply_order.py[line:801]: 放款完成或准备失败,目前的订单状态是30
INFO - 2021-11-30 17:01:37,014 - new_apply_order.py[line:802]: {'app': 'kencash', 'loan_order_id': '1465606858747940864', 'mobile': '738262872', 'order_status': 30}
INFO - 2021-11-30 17:01:37,014 - new_apply_order.py[line:922]: ===========完成第【1】次进件===========
INFO - 2021-11-30 17:01:37,014 - new_apply_order.py[line:925]: ======完成第【1】次进件,耗时24.26s=====
