INFO - 2021-08-31 13:43:33,599 - new_apply_order.py[line:517]: 开始第 borrowme【1】次进件……
INFO - 2021-08-31 13:43:33,600 - new_apply_order.py[line:79]: ======【nga测试环境】生成手机号：01630388613 ======
INFO - 2021-08-31 13:43:34,014 - new_apply_order.py[line:86]: 01630388613 检测用户存在成功！
INFO - 2021-08-31 13:43:34,165 - new_apply_order.py[line:93]: 01630388613 短信发送成功！
INFO - 2021-08-31 13:43:34,225 - new_apply_order.py[line:103]: 01630388613 注册成功！
INFO - 2021-08-31 13:43:34,325 - new_apply_order.py[line:113]: 01630388613 短信发送成功！
ERROR - 2021-08-31 13:43:34,392 - new_apply_order.py[line:128]: 登录失败!
INFO - 2021-08-31 13:43:34,478 - new_apply_order.py[line:172]: 个人信息提交成功！
INFO - 2021-08-31 13:43:34,548 - new_apply_order.py[line:181]: 联系人信息提交成功！
ERROR - 2021-08-31 13:43:34,715 - new_apply_order.py[line:200]: 创建预审失败{"code":"9999","msg":"The Server is busy, Please try again later","data":null}
INFO - 2021-08-31 13:43:34,727 - new_apply_order.py[line:206]: 预审状态修改为通过,更新条数 0
INFO - 2021-08-31 13:43:34,735 - new_apply_order.py[line:209]: 更新初始额度！更新条数 0
INFO - 2021-08-31 13:43:35,052 - new_apply_order.py[line:221]: 活体图片上传成功！回写配置文件global_param.mp4_url
INFO - 2021-08-31 13:43:35,092 - new_apply_order.py[line:230]: 视频认证通过！
INFO - 2021-08-31 13:43:36,312 - new_apply_order.py[line:276]: bvn和银行卡绑卡认证通过！
INFO - 2021-08-31 13:43:36,610 - new_apply_order.py[line:297]: user更新1条
ERROR - 2021-08-31 13:43:36,944 - new_apply_order.py[line:325]: {"code":"50001004","msg":"Not eligible for borrowing","data":null}
INFO - 2021-08-31 13:43:37,471 - new_apply_order.py[line:332]: 查询loan_order_id成功！
INFO - 2021-08-31 13:43:37,596 - new_apply_order.py[line:342]: 订单回调复审通过成功！
INFO - 2021-08-31 13:43:38,484 - new_apply_order.py[line:358]: 获取token成功！token=bearer bf51653c-283e-47c5-b902-66a96a35688d！
INFO - 2021-08-31 13:43:38,908 - new_apply_order.py[line:332]: 查询loan_order_id成功！
INFO - 2021-08-31 13:43:39,479 - new_apply_order.py[line:370]: 后台已触发放款成功！
INFO - 2021-08-31 13:43:39,485 - new_apply_order.py[line:378]: xxl_job web 登录成功！
INFO - 2021-08-31 13:43:39,491 - new_apply_order.py[line:385]: xxl_job 放款准备作业执行成功！
INFO - 2021-08-31 13:43:40,916 - new_apply_order.py[line:332]: 查询loan_order_id成功！
INFO - 2021-08-31 13:43:40,936 - new_apply_order.py[line:390]: 修改放款准备完成时间成功！
INFO - 2021-08-31 13:43:40,944 - new_apply_order.py[line:393]: xxl_job 放款完成作业执行成功！
INFO - 2021-08-31 13:43:41,250 - new_apply_order.py[line:540]: 校验重试查询第1次
ERROR - 2021-08-31 13:43:42,269 - new_apply_order.py[line:436]: 放款完成或准备失败,目前的订单状态是32
INFO - 2021-08-31 13:43:42,269 - new_apply_order.py[line:437]: {'app': 'borrowme', 'loan_order_id': '1432507683397570560', 'mobile': '01630371420', 'order_status': 32}
INFO - 2021-08-31 13:43:42,279 - new_apply_order.py[line:378]: xxl_job web 登录成功！
INFO - 2021-08-31 13:43:42,287 - new_apply_order.py[line:385]: xxl_job 放款准备作业执行成功！
INFO - 2021-08-31 13:43:43,703 - new_apply_order.py[line:332]: 查询loan_order_id成功！
INFO - 2021-08-31 13:43:43,714 - new_apply_order.py[line:390]: 修改放款准备完成时间成功！
INFO - 2021-08-31 13:43:43,718 - new_apply_order.py[line:393]: xxl_job 放款完成作业执行成功！
INFO - 2021-08-31 13:43:44,223 - new_apply_order.py[line:540]: 校验重试查询第2次
ERROR - 2021-08-31 13:43:45,240 - new_apply_order.py[line:436]: 放款完成或准备失败,目前的订单状态是32
INFO - 2021-08-31 13:43:45,241 - new_apply_order.py[line:437]: {'app': 'borrowme', 'loan_order_id': '1432507683397570560', 'mobile': '01630371420', 'order_status': 32}
INFO - 2021-08-31 13:43:45,249 - new_apply_order.py[line:378]: xxl_job web 登录成功！
INFO - 2021-08-31 13:43:45,256 - new_apply_order.py[line:385]: xxl_job 放款准备作业执行成功！
INFO - 2021-08-31 13:43:46,683 - new_apply_order.py[line:332]: 查询loan_order_id成功！
INFO - 2021-08-31 13:43:46,695 - new_apply_order.py[line:390]: 修改放款准备完成时间成功！
INFO - 2021-08-31 13:43:46,703 - new_apply_order.py[line:393]: xxl_job 放款完成作业执行成功！
INFO - 2021-08-31 13:43:47,204 - new_apply_order.py[line:540]: 校验重试查询第3次
ERROR - 2021-08-31 13:43:48,220 - new_apply_order.py[line:436]: 放款完成或准备失败,目前的订单状态是32
INFO - 2021-08-31 13:43:48,221 - new_apply_order.py[line:437]: {'app': 'borrowme', 'loan_order_id': '1432507683397570560', 'mobile': '01630371420', 'order_status': 32}
INFO - 2021-08-31 13:43:48,230 - new_apply_order.py[line:378]: xxl_job web 登录成功！
INFO - 2021-08-31 13:43:48,239 - new_apply_order.py[line:385]: xxl_job 放款准备作业执行成功！
INFO - 2021-08-31 13:43:49,703 - new_apply_order.py[line:332]: 查询loan_order_id成功！
INFO - 2021-08-31 13:43:49,716 - new_apply_order.py[line:390]: 修改放款准备完成时间成功！
INFO - 2021-08-31 13:43:49,722 - new_apply_order.py[line:393]: xxl_job 放款完成作业执行成功！
INFO - 2021-08-31 13:43:50,223 - new_apply_order.py[line:540]: 校验重试查询第4次
ERROR - 2021-08-31 13:43:51,239 - new_apply_order.py[line:436]: 放款完成或准备失败,目前的订单状态是32
INFO - 2021-08-31 13:43:51,239 - new_apply_order.py[line:437]: {'app': 'borrowme', 'loan_order_id': '1432507683397570560', 'mobile': '01630371420', 'order_status': 32}
INFO - 2021-08-31 13:43:51,248 - new_apply_order.py[line:378]: xxl_job web 登录成功！
INFO - 2021-08-31 13:43:51,257 - new_apply_order.py[line:385]: xxl_job 放款准备作业执行成功！
INFO - 2021-08-31 13:43:52,699 - new_apply_order.py[line:332]: 查询loan_order_id成功！
INFO - 2021-08-31 13:43:52,715 - new_apply_order.py[line:390]: 修改放款准备完成时间成功！
INFO - 2021-08-31 13:43:52,723 - new_apply_order.py[line:393]: xxl_job 放款完成作业执行成功！
INFO - 2021-08-31 13:43:53,228 - new_apply_order.py[line:540]: 校验重试查询第5次
ERROR - 2021-08-31 13:43:54,243 - new_apply_order.py[line:436]: 放款完成或准备失败,目前的订单状态是32
INFO - 2021-08-31 13:43:54,243 - new_apply_order.py[line:437]: {'app': 'borrowme', 'loan_order_id': '1432507683397570560', 'mobile': '01630371420', 'order_status': 32}
INFO - 2021-08-31 13:43:54,251 - new_apply_order.py[line:378]: xxl_job web 登录成功！
INFO - 2021-08-31 13:43:54,259 - new_apply_order.py[line:385]: xxl_job 放款准备作业执行成功！
INFO - 2021-08-31 13:43:55,679 - new_apply_order.py[line:332]: 查询loan_order_id成功！
INFO - 2021-08-31 13:43:55,702 - new_apply_order.py[line:390]: 修改放款准备完成时间成功！
INFO - 2021-08-31 13:43:55,711 - new_apply_order.py[line:393]: xxl_job 放款完成作业执行成功！
INFO - 2021-08-31 13:43:56,216 - new_apply_order.py[line:540]: 校验重试查询第6次
ERROR - 2021-08-31 13:43:57,232 - new_apply_order.py[line:436]: 放款完成或准备失败,目前的订单状态是32
INFO - 2021-08-31 13:43:57,232 - new_apply_order.py[line:437]: {'app': 'borrowme', 'loan_order_id': '1432507683397570560', 'mobile': '01630371420', 'order_status': 32}
INFO - 2021-08-31 13:43:57,244 - new_apply_order.py[line:378]: xxl_job web 登录成功！
INFO - 2021-08-31 13:43:57,253 - new_apply_order.py[line:385]: xxl_job 放款准备作业执行成功！
INFO - 2021-08-31 13:43:58,676 - new_apply_order.py[line:332]: 查询loan_order_id成功！
INFO - 2021-08-31 13:43:58,691 - new_apply_order.py[line:390]: 修改放款准备完成时间成功！
INFO - 2021-08-31 13:43:58,698 - new_apply_order.py[line:393]: xxl_job 放款完成作业执行成功！
INFO - 2021-08-31 13:43:59,202 - new_apply_order.py[line:540]: 校验重试查询第7次
ERROR - 2021-08-31 13:44:00,219 - new_apply_order.py[line:436]: 放款完成或准备失败,目前的订单状态是32
INFO - 2021-08-31 13:44:00,220 - new_apply_order.py[line:437]: {'app': 'borrowme', 'loan_order_id': '1432507683397570560', 'mobile': '01630371420', 'order_status': 32}
INFO - 2021-08-31 13:44:00,228 - new_apply_order.py[line:378]: xxl_job web 登录成功！
INFO - 2021-08-31 13:44:00,238 - new_apply_order.py[line:385]: xxl_job 放款准备作业执行成功！
INFO - 2021-08-31 13:44:01,660 - new_apply_order.py[line:332]: 查询loan_order_id成功！
INFO - 2021-08-31 13:44:01,678 - new_apply_order.py[line:390]: 修改放款准备完成时间成功！
INFO - 2021-08-31 13:44:01,688 - new_apply_order.py[line:393]: xxl_job 放款完成作业执行成功！
INFO - 2021-08-31 13:44:02,191 - new_apply_order.py[line:540]: 校验重试查询第8次
ERROR - 2021-08-31 13:44:03,207 - new_apply_order.py[line:436]: 放款完成或准备失败,目前的订单状态是32
INFO - 2021-08-31 13:44:03,208 - new_apply_order.py[line:437]: {'app': 'borrowme', 'loan_order_id': '1432507683397570560', 'mobile': '01630371420', 'order_status': 32}
INFO - 2021-08-31 13:44:03,216 - new_apply_order.py[line:378]: xxl_job web 登录成功！
INFO - 2021-08-31 13:44:03,222 - new_apply_order.py[line:385]: xxl_job 放款准备作业执行成功！
INFO - 2021-08-31 13:44:04,644 - new_apply_order.py[line:332]: 查询loan_order_id成功！
INFO - 2021-08-31 13:44:04,660 - new_apply_order.py[line:390]: 修改放款准备完成时间成功！
INFO - 2021-08-31 13:44:04,667 - new_apply_order.py[line:393]: xxl_job 放款完成作业执行成功！
INFO - 2021-08-31 13:44:05,169 - new_apply_order.py[line:540]: 校验重试查询第9次
ERROR - 2021-08-31 13:44:06,188 - new_apply_order.py[line:436]: 放款完成或准备失败,目前的订单状态是32
INFO - 2021-08-31 13:44:06,189 - new_apply_order.py[line:437]: {'app': 'borrowme', 'loan_order_id': '1432507683397570560', 'mobile': '01630371420', 'order_status': 32}
INFO - 2021-08-31 13:44:06,199 - new_apply_order.py[line:378]: xxl_job web 登录成功！
INFO - 2021-08-31 13:44:06,207 - new_apply_order.py[line:385]: xxl_job 放款准备作业执行成功！
INFO - 2021-08-31 13:44:07,635 - new_apply_order.py[line:332]: 查询loan_order_id成功！
INFO - 2021-08-31 13:44:07,651 - new_apply_order.py[line:390]: 修改放款准备完成时间成功！
INFO - 2021-08-31 13:44:07,657 - new_apply_order.py[line:393]: xxl_job 放款完成作业执行成功！
INFO - 2021-08-31 13:44:08,161 - new_apply_order.py[line:540]: 校验重试查询第10次
ERROR - 2021-08-31 13:44:09,179 - new_apply_order.py[line:436]: 放款完成或准备失败,目前的订单状态是32
INFO - 2021-08-31 13:44:09,180 - new_apply_order.py[line:437]: {'app': 'borrowme', 'loan_order_id': '1432507683397570560', 'mobile': '01630371420', 'order_status': 32}
INFO - 2021-08-31 13:44:09,189 - new_apply_order.py[line:378]: xxl_job web 登录成功！
INFO - 2021-08-31 13:44:09,196 - new_apply_order.py[line:385]: xxl_job 放款准备作业执行成功！
INFO - 2021-08-31 13:44:10,616 - new_apply_order.py[line:332]: 查询loan_order_id成功！
INFO - 2021-08-31 13:44:10,631 - new_apply_order.py[line:390]: 修改放款准备完成时间成功！
INFO - 2021-08-31 13:44:10,638 - new_apply_order.py[line:393]: xxl_job 放款完成作业执行成功！
INFO - 2021-08-31 13:44:11,139 - new_apply_order.py[line:557]: ===========完成第【1】次进件===========
INFO - 2021-08-31 13:44:11,140 - new_apply_order.py[line:560]: ======完成第【1】次进件,耗时37.54s=====
