INFO - 2022-01-04 21:15:23,751 - new_apply_order.py[line:929]: 开始第 aceloan【1】次进件……
INFO - 2022-01-04 21:15:24,163 - new_apply_order.py[line:95]: 01634872789 检测用户存在成功！
INFO - 2022-01-04 21:15:24,253 - new_apply_order.py[line:104]: 01634872789 短信发送成功！
ERROR - 2022-01-04 21:15:24,299 - new_apply_order.py[line:119]: 注册失败！{'accept': 'application/json', 'appversion': '1.3.0.9', 'devtoken': 'cb95881f542ac58170:BB:E9:91:D3:CD', 'accept-language': 'en-US', 'clientCode': 'aceloani1300', 'Content-Type': 'application/json; charset=UTF-8', 'Host': '172.20.240.143:8012', 'User-Agent': 'okhttp/4.9.0'}
ERROR - 2022-01-04 21:15:24,300 - new_apply_order.py[line:120]: {"code":"20001003","msg":"This number already exists, please use another number","data":null}
INFO - 2022-01-04 21:15:24,381 - new_apply_order.py[line:133]: 01634872789 登录短信发送成功！
INFO - 2022-01-04 21:15:24,472 - new_apply_order.py[line:143]: userId=6249743425571135488,mobile=01634872789,token=bbd54350a13e03363f8314aa91d93458 登录成功
INFO - 2022-01-04 21:15:24,558 - new_apply_order.py[line:210]: 个人信息提交成功！
INFO - 2022-01-04 21:15:24,632 - new_apply_order.py[line:221]: 联系人信息提交成功！
ERROR - 2022-01-04 21:15:24,802 - new_apply_order.py[line:255]: 创建预审失败{"code":"9999","msg":"The Server is busy, Please try again later","data":null}
INFO - 2022-01-04 21:15:24,888 - new_apply_order.py[line:261]: 预审状态修改为通过,更新条数 0
INFO - 2022-01-04 21:15:24,975 - new_apply_order.py[line:264]: 更新初始额度！更新条数 0
INFO - 2022-01-04 21:15:25,321 - new_apply_order.py[line:340]: 活体图片上传成功！回写配置文件global_param.mp4_url
INFO - 2022-01-04 21:15:25,372 - new_apply_order.py[line:350]: 视频认证通过！
INFO - 2022-01-04 21:15:26,383 - new_apply_order.py[line:509]: bvn和银行卡绑卡认证通过！
INFO - 2022-01-04 21:15:26,984 - new_apply_order.py[line:560]: user更新1条
ERROR - 2022-01-04 21:15:27,229 - new_apply_order.py[line:629]: {"code":"50001004","msg":"Not eligible for borrowing","data":null}
INFO - 2022-01-04 21:15:27,792 - new_apply_order.py[line:641]: 查询loan_order_id成功！
INFO - 2022-01-04 21:15:27,820 - new_apply_order.py[line:656]: 订单回调复审通过成功！
INFO - 2022-01-04 21:15:28,602 - new_apply_order.py[line:678]: 获取token成功！token=bearer 8b726839-f78d-4bfc-a13d-d98083b7d78e！
INFO - 2022-01-04 21:15:29,138 - new_apply_order.py[line:641]: 查询loan_order_id成功！
INFO - 2022-01-04 21:15:29,505 - new_apply_order.py[line:696]: 后台已触发放款成功！
INFO - 2022-01-04 21:15:29,531 - new_apply_order.py[line:710]: xxl_job web 登录成功！
INFO - 2022-01-04 21:15:29,550 - new_apply_order.py[line:726]: xxl_job 放款准备作业执行成功！
INFO - 2022-01-04 21:15:31,020 - new_apply_order.py[line:641]: 查询loan_order_id成功！
INFO - 2022-01-04 21:15:31,052 - new_apply_order.py[line:734]: 修改放款准备完成时间成功！
INFO - 2022-01-04 21:15:31,062 - new_apply_order.py[line:742]: xxl_job 放款完成作业执行成功！
INFO - 2022-01-04 21:15:31,373 - new_apply_order.py[line:952]: 校验重试查询第1次
ERROR - 2022-01-04 21:15:32,393 - new_apply_order.py[line:810]: 放款完成或准备失败,目前的订单状态是32
INFO - 2022-01-04 21:15:32,393 - new_apply_order.py[line:811]: {'app': 'aceloan', 'loan_order_id': '1478353983593910272', 'mobile': '01634872789', 'order_status': 32}
INFO - 2022-01-04 21:15:32,407 - new_apply_order.py[line:710]: xxl_job web 登录成功！
INFO - 2022-01-04 21:15:32,418 - new_apply_order.py[line:726]: xxl_job 放款准备作业执行成功！
INFO - 2022-01-04 21:15:33,893 - new_apply_order.py[line:641]: 查询loan_order_id成功！
INFO - 2022-01-04 21:15:33,924 - new_apply_order.py[line:734]: 修改放款准备完成时间成功！
INFO - 2022-01-04 21:15:33,935 - new_apply_order.py[line:742]: xxl_job 放款完成作业执行成功！
INFO - 2022-01-04 21:15:34,440 - new_apply_order.py[line:952]: 校验重试查询第2次
ERROR - 2022-01-04 21:15:35,460 - new_apply_order.py[line:810]: 放款完成或准备失败,目前的订单状态是32
INFO - 2022-01-04 21:15:35,460 - new_apply_order.py[line:811]: {'app': 'aceloan', 'loan_order_id': '1478353983593910272', 'mobile': '01634872789', 'order_status': 32}
INFO - 2022-01-04 21:15:35,480 - new_apply_order.py[line:710]: xxl_job web 登录成功！
INFO - 2022-01-04 21:15:35,496 - new_apply_order.py[line:726]: xxl_job 放款准备作业执行成功！
INFO - 2022-01-04 21:15:36,949 - new_apply_order.py[line:641]: 查询loan_order_id成功！
INFO - 2022-01-04 21:15:36,973 - new_apply_order.py[line:734]: 修改放款准备完成时间成功！
INFO - 2022-01-04 21:15:36,981 - new_apply_order.py[line:742]: xxl_job 放款完成作业执行成功！
INFO - 2022-01-04 21:15:37,486 - new_apply_order.py[line:952]: 校验重试查询第3次
ERROR - 2022-01-04 21:15:38,558 - new_apply_order.py[line:810]: 放款完成或准备失败,目前的订单状态是32
INFO - 2022-01-04 21:15:38,559 - new_apply_order.py[line:811]: {'app': 'aceloan', 'loan_order_id': '1478353983593910272', 'mobile': '01634872789', 'order_status': 32}
INFO - 2022-01-04 21:15:38,592 - new_apply_order.py[line:710]: xxl_job web 登录成功！
INFO - 2022-01-04 21:15:38,613 - new_apply_order.py[line:726]: xxl_job 放款准备作业执行成功！
INFO - 2022-01-04 21:15:40,087 - new_apply_order.py[line:641]: 查询loan_order_id成功！
INFO - 2022-01-04 21:15:40,169 - new_apply_order.py[line:734]: 修改放款准备完成时间成功！
INFO - 2022-01-04 21:15:40,192 - new_apply_order.py[line:742]: xxl_job 放款完成作业执行成功！
INFO - 2022-01-04 21:15:40,693 - new_apply_order.py[line:952]: 校验重试查询第4次
ERROR - 2022-01-04 21:15:41,770 - new_apply_order.py[line:810]: 放款完成或准备失败,目前的订单状态是32
INFO - 2022-01-04 21:15:41,771 - new_apply_order.py[line:811]: {'app': 'aceloan', 'loan_order_id': '1478353983593910272', 'mobile': '01634872789', 'order_status': 32}
INFO - 2022-01-04 21:15:41,812 - new_apply_order.py[line:710]: xxl_job web 登录成功！
INFO - 2022-01-04 21:15:41,845 - new_apply_order.py[line:726]: xxl_job 放款准备作业执行成功！
INFO - 2022-01-04 21:15:43,349 - new_apply_order.py[line:641]: 查询loan_order_id成功！
INFO - 2022-01-04 21:15:43,420 - new_apply_order.py[line:734]: 修改放款准备完成时间成功！
INFO - 2022-01-04 21:15:43,440 - new_apply_order.py[line:742]: xxl_job 放款完成作业执行成功！
INFO - 2022-01-04 21:15:43,945 - new_apply_order.py[line:952]: 校验重试查询第5次
ERROR - 2022-01-04 21:15:45,010 - new_apply_order.py[line:810]: 放款完成或准备失败,目前的订单状态是32
INFO - 2022-01-04 21:15:45,011 - new_apply_order.py[line:811]: {'app': 'aceloan', 'loan_order_id': '1478353983593910272', 'mobile': '01634872789', 'order_status': 32}
INFO - 2022-01-04 21:15:45,047 - new_apply_order.py[line:710]: xxl_job web 登录成功！
INFO - 2022-01-04 21:15:45,070 - new_apply_order.py[line:726]: xxl_job 放款准备作业执行成功！
INFO - 2022-01-04 21:15:46,533 - new_apply_order.py[line:641]: 查询loan_order_id成功！
INFO - 2022-01-04 21:15:46,588 - new_apply_order.py[line:734]: 修改放款准备完成时间成功！
INFO - 2022-01-04 21:15:46,598 - new_apply_order.py[line:742]: xxl_job 放款完成作业执行成功！
INFO - 2022-01-04 21:15:47,103 - new_apply_order.py[line:952]: 校验重试查询第6次
ERROR - 2022-01-04 21:15:48,160 - new_apply_order.py[line:810]: 放款完成或准备失败,目前的订单状态是32
INFO - 2022-01-04 21:15:48,161 - new_apply_order.py[line:811]: {'app': 'aceloan', 'loan_order_id': '1478353983593910272', 'mobile': '01634872789', 'order_status': 32}
INFO - 2022-01-04 21:15:48,199 - new_apply_order.py[line:710]: xxl_job web 登录成功！
INFO - 2022-01-04 21:15:48,220 - new_apply_order.py[line:726]: xxl_job 放款准备作业执行成功！
INFO - 2022-01-04 21:15:49,699 - new_apply_order.py[line:641]: 查询loan_order_id成功！
INFO - 2022-01-04 21:15:49,765 - new_apply_order.py[line:734]: 修改放款准备完成时间成功！
INFO - 2022-01-04 21:15:49,781 - new_apply_order.py[line:742]: xxl_job 放款完成作业执行成功！
INFO - 2022-01-04 21:15:50,282 - new_apply_order.py[line:952]: 校验重试查询第7次
ERROR - 2022-01-04 21:15:51,353 - new_apply_order.py[line:810]: 放款完成或准备失败,目前的订单状态是32
INFO - 2022-01-04 21:15:51,354 - new_apply_order.py[line:811]: {'app': 'aceloan', 'loan_order_id': '1478353983593910272', 'mobile': '01634872789', 'order_status': 32}
INFO - 2022-01-04 21:15:51,379 - new_apply_order.py[line:710]: xxl_job web 登录成功！
INFO - 2022-01-04 21:15:51,399 - new_apply_order.py[line:726]: xxl_job 放款准备作业执行成功！
INFO - 2022-01-04 21:15:52,872 - new_apply_order.py[line:641]: 查询loan_order_id成功！
INFO - 2022-01-04 21:15:52,989 - new_apply_order.py[line:734]: 修改放款准备完成时间成功！
INFO - 2022-01-04 21:15:53,013 - new_apply_order.py[line:742]: xxl_job 放款完成作业执行成功！
INFO - 2022-01-04 21:15:53,519 - new_apply_order.py[line:952]: 校验重试查询第8次
ERROR - 2022-01-04 21:15:54,599 - new_apply_order.py[line:810]: 放款完成或准备失败,目前的订单状态是32
INFO - 2022-01-04 21:15:54,599 - new_apply_order.py[line:811]: {'app': 'aceloan', 'loan_order_id': '1478353983593910272', 'mobile': '01634872789', 'order_status': 32}
INFO - 2022-01-04 21:15:54,641 - new_apply_order.py[line:710]: xxl_job web 登录成功！
INFO - 2022-01-04 21:15:54,660 - new_apply_order.py[line:726]: xxl_job 放款准备作业执行成功！
INFO - 2022-01-04 21:15:56,154 - new_apply_order.py[line:641]: 查询loan_order_id成功！
INFO - 2022-01-04 21:15:56,230 - new_apply_order.py[line:734]: 修改放款准备完成时间成功！
INFO - 2022-01-04 21:15:56,253 - new_apply_order.py[line:742]: xxl_job 放款完成作业执行成功！
INFO - 2022-01-04 21:15:56,756 - new_apply_order.py[line:952]: 校验重试查询第9次
ERROR - 2022-01-04 21:15:57,829 - new_apply_order.py[line:810]: 放款完成或准备失败,目前的订单状态是32
INFO - 2022-01-04 21:15:57,830 - new_apply_order.py[line:811]: {'app': 'aceloan', 'loan_order_id': '1478353983593910272', 'mobile': '01634872789', 'order_status': 32}
INFO - 2022-01-04 21:15:57,882 - new_apply_order.py[line:710]: xxl_job web 登录成功！
INFO - 2022-01-04 21:15:57,903 - new_apply_order.py[line:726]: xxl_job 放款准备作业执行成功！
INFO - 2022-01-04 21:15:59,430 - new_apply_order.py[line:641]: 查询loan_order_id成功！
INFO - 2022-01-04 21:15:59,473 - new_apply_order.py[line:734]: 修改放款准备完成时间成功！
INFO - 2022-01-04 21:15:59,486 - new_apply_order.py[line:742]: xxl_job 放款完成作业执行成功！
INFO - 2022-01-04 21:15:59,991 - new_apply_order.py[line:952]: 校验重试查询第10次
ERROR - 2022-01-04 21:16:01,068 - new_apply_order.py[line:810]: 放款完成或准备失败,目前的订单状态是32
INFO - 2022-01-04 21:16:01,069 - new_apply_order.py[line:811]: {'app': 'aceloan', 'loan_order_id': '1478353983593910272', 'mobile': '01634872789', 'order_status': 32}
INFO - 2022-01-04 21:16:01,123 - new_apply_order.py[line:710]: xxl_job web 登录成功！
INFO - 2022-01-04 21:16:01,152 - new_apply_order.py[line:726]: xxl_job 放款准备作业执行成功！
INFO - 2022-01-04 21:16:02,598 - new_apply_order.py[line:641]: 查询loan_order_id成功！
INFO - 2022-01-04 21:16:02,623 - new_apply_order.py[line:734]: 修改放款准备完成时间成功！
INFO - 2022-01-04 21:16:02,631 - new_apply_order.py[line:742]: xxl_job 放款完成作业执行成功！
INFO - 2022-01-04 21:16:03,133 - new_apply_order.py[line:969]: ===========完成第【1】次进件===========
INFO - 2022-01-04 21:16:03,134 - new_apply_order.py[line:972]: ======完成第【1】次进件,耗时39.38s=====
INFO - 2022-01-04 21:16:03,621 - new_apply_order.py[line:678]: 获取token成功！token=bearer 8b726839-f78d-4bfc-a13d-d98083b7d78e！
INFO - 2022-01-04 21:16:04,217 - new_apply_order.py[line:678]: 获取token成功！token=bearer 8b726839-f78d-4bfc-a13d-d98083b7d78e！
INFO - 2022-01-04 21:16:04,721 - new_apply_order.py[line:894]: {'code': '10099001', 'msg': 'Service Currently Unavailable', 'notSuccess': True, 'success': False}
ERROR - 2022-01-04 21:16:04,722 - new_apply_order.py[line:976]: 'data'
ERROR - 2022-01-04 21:16:04,723 - new_apply_order.py[line:977]: None
